# Данная сборка нужна исключительно для локальной проверки,
# в продакшн среде подъём приложения будет осуществляться за счёт kubernetes ресурсов и чартов Helm.
services:
  db:
    container_name: manager_db
    image: postgis/postgis:17-3.4-alpine
    volumes:
      - ./data_value:/var/lib/postgresql/data/
    env_file:
      - .env
    #    ports:
    #      - "5432:5432" # Для локального тестового подключения и дебага.
    networks:
      rlg_network:
        ipv4_address: 172.25.0.3


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #    ports:
    #      - "9200:9200" # Для локального тестового подключения и дебага.
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      rlg_network:
        ipv4_address: 172.25.0.4

  bet_maker:
    container_name: manager_backend
    build: manager/.
    ports:
      - "8000:8000" # Порт открыт исключительно в тестовых целях, для проверки эндпоинтов через API интерфейс!
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - db
    networks:
      rlg_network:
        ipv4_address: 172.25.0.5

networks:
  rlg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  data_value:
  es_data:
    driver: local